# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Disable newline
add_newline = false
# A minimal left prompt
format = """$directory$character"""
# Move the rest of the prompt to the right
right_format = """$all"""

[aws]
disabled = true

